version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - misspell
    - unconvert
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - fmt.Fprint
        - fmt.Fprintln
        - fmt.Fprintf
        - os.RemoveAll
  exclusions:
    presets:
      - comments
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - bodyclose

formatters:
  enable:
    - gofmt
    - goimports
