// Package install writes a merged configuration into the workspace so that
// editors which launch dev containers on their own can pick it up.
//
// Two modes exist because editors disagree on where they look:
//
//   - ModeProfile writes .devcontainer/<name>/devcontainer.json. VS Code,
//     Codespaces and Zed all offer sub-folder configs in a picker. Nothing in
//     the repo's own files changes. Zed additionally needs the directory in
//     its file_scan_inclusions setting, because it does not scan inside
//     git-ignored directories.
//   - ModeInPlace replaces .devcontainer/devcontainer.json itself, keeping the
//     original in .devcontainer/.dcp/base.json and marking the tracked file
//     skip-worktree. Use it for tools that read only the canonical path — the
//     reference CLI auto-discovers exactly two locations — or to avoid the
//     editor-side configuration that profile mode can require.
package install

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/clamoriniere/devcontainer-patcher/internal/dcpath"
	"github.com/clamoriniere/devcontainer-patcher/internal/jsonx"
	"github.com/clamoriniere/devcontainer-patcher/internal/merge"
)

// Mode selects where the generated config is written.
type Mode string

const (
	ModeProfile Mode = "profile"
	ModeInPlace Mode = "in-place"
)

const (
	// StateDir holds the backups and bookkeeping for an installation.
	StateDir  = ".dcp"
	stateFile = "state.json"
	// DefaultProfileName is the sub-folder used by ModeProfile.
	DefaultProfileName = "local"

	header = "// Generated by devcontainer-patcher. Do not edit.\n" +
		"// Edit your overlay instead, then re-run `dcp install`.\n" +
		"// `dcp uninstall` restores the original file.\n"
)

// State is persisted next to the generated config so uninstall and status can
// work without re-deriving anything.
type State struct {
	Mode          Mode     `json:"mode"`
	ProfileName   string   `json:"profileName,omitempty"`
	BasePath      string   `json:"basePath"`      // workspace-relative
	GeneratedPath string   `json:"generatedPath"` // workspace-relative
	BaseBackup    string   `json:"baseBackup,omitempty"`
	LockBackup    string   `json:"lockBackup,omitempty"`
	BaseSHA256    string   `json:"baseSha256"`
	SkipWorktree  []string `json:"skipWorktree,omitempty"`
	InstalledAt   string   `json:"installedAt"`
}

// Installer performs installs against one workspace.
type Installer struct {
	Workspace string
	// BasePath is the repo's committed devcontainer.json (absolute).
	BasePath string
	git      *git
}

func New(workspace, basePath string) *Installer {
	return &Installer{
		Workspace: workspace,
		BasePath:  basePath,
		git:       newGit(workspace),
	}
}

func (i *Installer) stateDir() string {
	return filepath.Join(filepath.Dir(i.BasePath), StateDir)
}

func (i *Installer) statePath() string {
	return filepath.Join(i.stateDir(), stateFile)
}

func (i *Installer) rel(path string) string {
	r, err := filepath.Rel(i.Workspace, path)
	if err != nil {
		return path
	}
	return filepath.ToSlash(r)
}

// LoadState reads the current installation, if any.
func (i *Installer) LoadState() (*State, error) {
	data, err := os.ReadFile(i.statePath())
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	var s State
	if err := json.Unmarshal(data, &s); err != nil {
		return nil, fmt.Errorf("%s: %w", i.statePath(), err)
	}
	return &s, nil
}

func (i *Installer) saveState(s *State) error {
	if err := os.MkdirAll(i.stateDir(), 0o755); err != nil {
		return err
	}
	data, err := json.MarshalIndent(s, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(i.statePath(), append(data, '\n'), 0o644)
}

// Install writes the merged result into the workspace using the requested mode.
func (i *Installer) Install(res *merge.Result, mode Mode, profileName string) (*State, error) {
	if existing, err := i.LoadState(); err != nil {
		return nil, err
	} else if existing != nil && existing.Mode != mode {
		return nil, fmt.Errorf("already installed in %q mode; run `dcp uninstall` first", existing.Mode)
	}

	switch mode {
	case ModeProfile:
		return i.installProfile(res, profileName)
	case ModeInPlace:
		return i.installInPlace(res.Config)
	default:
		return nil, fmt.Errorf("unknown install mode %q", mode)
	}
}

func (i *Installer) installProfile(res *merge.Result, name string) (*State, error) {
	if name == "" {
		name = DefaultProfileName
	}
	devcontainerDir := filepath.Dir(i.BasePath)
	targetDir := filepath.Join(devcontainerDir, name)
	target := filepath.Join(targetDir, "devcontainer.json")

	// The generated config sits one directory deeper than the original, so
	// build.dockerfile and friends must be re-anchored.
	doc := jsonx.Clone(res.Config).(map[string]any)
	dcpath.Rewrite(doc, devcontainerDir, targetDir)
	labelProfile(doc, res, name)

	if err := os.MkdirAll(targetDir, 0o755); err != nil {
		return nil, err
	}
	if err := writeConfig(target, doc); err != nil {
		return nil, err
	}

	baseSum, err := fileSHA256(i.BasePath)
	if err != nil {
		return nil, err
	}

	state := &State{
		Mode:          ModeProfile,
		ProfileName:   name,
		BasePath:      i.rel(i.BasePath),
		GeneratedPath: i.rel(target),
		BaseSHA256:    baseSum,
		InstalledAt:   time.Now().UTC().Format(time.RFC3339),
	}
	if err := i.saveState(state); err != nil {
		return nil, err
	}
	if err := i.git.exclude(i.rel(targetDir)+"/", i.rel(i.stateDir())+"/"); err != nil {
		return nil, err
	}
	return state, nil
}

func (i *Installer) installInPlace(merged map[string]any) (*State, error) {
	rel := i.rel(i.BasePath)
	prior, err := i.LoadState()
	if err != nil {
		return nil, err
	}

	// Refuse to bury edits the user has not committed. An existing install
	// reads as clean thanks to skip-worktree, so this only fires on real work.
	if prior == nil && i.git.dirty(rel) {
		return nil, fmt.Errorf("%s has uncommitted changes; commit or stash them before installing in-place", rel)
	}

	if err := os.MkdirAll(i.stateDir(), 0o755); err != nil {
		return nil, err
	}

	backup := filepath.Join(i.stateDir(), "base.json")
	if prior == nil {
		// First install: the file on disk is still the pristine original.
		if err := copyFile(i.BasePath, backup); err != nil {
			return nil, err
		}
	}
	baseSum, err := fileSHA256(backup)
	if err != nil {
		return nil, err
	}

	var skip []string
	state := &State{
		Mode:          ModeInPlace,
		BasePath:      rel,
		GeneratedPath: rel,
		BaseBackup:    i.rel(backup),
		BaseSHA256:    baseSum,
		InstalledAt:   time.Now().UTC().Format(time.RFC3339),
	}

	// The lockfile is written next to configFilePath, which in-place means the
	// committed .devcontainer/devcontainer-lock.json. Without this, personal
	// Features would leak into the repo's lockfile.
	lock := filepath.Join(filepath.Dir(i.BasePath), "devcontainer-lock.json")
	if _, err := os.Stat(lock); err == nil {
		lockBackup := filepath.Join(i.stateDir(), "devcontainer-lock.json")
		if prior == nil || prior.LockBackup == "" {
			if err := copyFile(lock, lockBackup); err != nil {
				return nil, err
			}
		}
		state.LockBackup = i.rel(lockBackup)
		if i.git.tracked(i.rel(lock)) {
			if err := i.git.setSkipWorktree(i.rel(lock), true); err == nil {
				skip = append(skip, i.rel(lock))
			}
		}
	}

	if err := writeConfig(i.BasePath, merged); err != nil {
		return nil, err
	}

	if i.git.tracked(rel) {
		if err := i.git.setSkipWorktree(rel, true); err != nil {
			return nil, fmt.Errorf("mark %s skip-worktree: %w", rel, err)
		}
		skip = append(skip, rel)
	}
	state.SkipWorktree = skip

	if err := i.saveState(state); err != nil {
		return nil, err
	}
	if err := i.git.exclude(i.rel(i.stateDir()) + "/"); err != nil {
		return nil, err
	}
	return state, nil
}

// Uninstall restores the workspace to its committed state.
func (i *Installer) Uninstall() (*State, error) {
	state, err := i.LoadState()
	if err != nil {
		return nil, err
	}
	if state == nil {
		return nil, nil
	}

	for _, rel := range state.SkipWorktree {
		// Clear the flag before restoring so git sees the restored content.
		if err := i.git.setSkipWorktree(rel, false); err != nil {
			return nil, fmt.Errorf("clear skip-worktree on %s: %w", rel, err)
		}
	}

	if state.Mode == ModeInPlace {
		if state.BaseBackup != "" {
			if err := copyFile(filepath.Join(i.Workspace, state.BaseBackup), i.BasePath); err != nil {
				return nil, fmt.Errorf("restore %s: %w", state.BasePath, err)
			}
		}
		if state.LockBackup != "" {
			lock := filepath.Join(filepath.Dir(i.BasePath), "devcontainer-lock.json")
			if err := copyFile(filepath.Join(i.Workspace, state.LockBackup), lock); err != nil {
				return nil, fmt.Errorf("restore lockfile: %w", err)
			}
		}
	} else {
		if err := os.RemoveAll(filepath.Dir(filepath.Join(i.Workspace, state.GeneratedPath))); err != nil {
			return nil, err
		}
	}

	if err := os.RemoveAll(i.stateDir()); err != nil {
		return nil, err
	}
	return state, nil
}

// BaseDrift reports whether the committed devcontainer.json changed since the
// install captured it, which means the generated file is stale.
func (i *Installer) BaseDrift(state *State) (drifted bool, known bool) {
	head, ok := i.git.headBlob(state.BasePath)
	if !ok {
		return false, false
	}
	sum := sha256.Sum256(head)
	return hex.EncodeToString(sum[:]) != state.BaseSHA256, true
}

// PristineBase returns the path holding the original committed config, which
// differs from BasePath while an in-place install is active.
func (i *Installer) PristineBase(state *State) string {
	if state != nil && state.Mode == ModeInPlace && state.BaseBackup != "" {
		return filepath.Join(i.Workspace, state.BaseBackup)
	}
	return i.BasePath
}

// labelProfile makes the generated config distinguishable in an editor's
// configuration picker. Without this it inherits the repo's "name" and shows up
// as a second entry with an identical label. An overlay that sets "name"
// itself is left alone.
func labelProfile(doc map[string]any, res *merge.Result, profile string) {
	prov := res.Provenance["name"]
	userNamed := len(prov) > 0 && prov[len(prov)-1] != "repo"
	if userNamed {
		return
	}
	if current, ok := doc["name"].(string); ok && current != "" {
		doc["name"] = fmt.Sprintf("%s (%s)", current, profile)
		return
	}
	doc["name"] = profile
}

func writeConfig(path string, doc map[string]any) error {
	data, err := jsonx.Marshal(doc)
	if err != nil {
		return err
	}
	return os.WriteFile(path, append([]byte(header), data...), 0o644)
}

func copyFile(src, dst string) error {
	data, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return err
	}
	return os.WriteFile(dst, data, 0o644)
}

func fileSHA256(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:]), nil
}
